apiVersion: '2021-09-01'
name: audio-transcription-instance
identity:
  type: UserAssigned
  userAssignedIdentities:
    /subscriptions/18d0f347-c2a3-45b7-91bb-10bd4b76f188/resourceGroups/rg-aistuff-shr-eus/providers/Microsoft.ManagedIdentity/userAssignedIdentities/e2be593c-50b6-4d41-ba29-1f0f0e39645b: {}
properties:
  containers:
  - name: audio-transcription-container
    properties:
      image: craistuff.azurecr.io/audio-transcription:latest
      resources:
        requests:
          cpu: 4.0
          memoryInGB: 16.0
      ports:
      - port: 8080
  osType: Linux
  restartPolicy: OnFailure
